services:
  db:
    platform: linux/x86_64
    user: root
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'assignment'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - social_media_app-master_my-network

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: db  # Use the service name 'db' instead of 'localhost'
    networks:
      - social_media_app-master_my-network

networks:
  social_media_app-master_my-network:
    driver: bridge
